### PR TITLE
SVNKIT-670 , JENKINS-15376  : Fixing memory leak

### PR DESCRIPTION
**Pull request by 2improveIT**
Fix for JENKINS-15376 : memory leak in getTags

### CODE REVIEW

**Comment by 2improveIT** [comment]
All Jenkins errors are due to a testing error : not introduced with this fix

Checking out https://svn.jenkins-ci.org/trunk/hudson/test-projects/trivial-ant at revision '2016-06-14T11:43:47.249 -0400'
ERROR: Failed to check out https://svn.jenkins-ci.org/trunk/hudson/test-projects/trivial-ant
&#27;[8mha:AAAAWB+LCAAAAAAAAP9b85aBtbiIQSmjNKU4P08vOT+vOD8nVc8DzHWtSE4tKMnMz/PLL0ldFVf2c+b/lb5MDAwVRQxSaBqcITRIIQMEMIIUFgAAckCEiWAAAAA=&#27;[0morg.tmatesoft.svn.core.SVNException: svn: E175002: PROPFIND of '/trunk/hudson/test-projects/trivial-ant': 405 Method Not Allowed

**Comment by jglick** [comment]
Is the same as #166?

**Comment by oleg-nenashev** [comment]
@jglick Same. This one is better since it properly checks for null

**Comment by wborn** [comment]
This PR can be closed since #196 already got merged.

**Pull request closed without merging**
