### PR TITLE
Add commit times support

### PR DESCRIPTION
**Pull request by ekesseler**
Applied your change requests from: https://github.com/jenkinsci/subversion-plugin/pull/64/files

Please approve and add this to the next version or give me feedback.

Thank you

### CODE REVIEW

**Comment by christ66** [comment]
:-1: One of the commits has a user.name of `unknown`.

**Comment by ekesseler** [comment]
Please tell me how to change it.

**Comment by daniel-beck** [comment]
@ekesseler Why did you close this PR?

**Comment by ekesseler** [comment]
Since the changing of the user.name was complicated, it was easier for me to close this one and open a new pull request: https://github.com/jenkinsci/subversion-plugin/pull/116

Which failed because of timeouts which are unrelated to the commit. Maybe you can check it out.

**Pull request closed without merging**
