### PR TITLE
Check EXTENDED_READ, not CONFIGURE, on a context

### PR DESCRIPTION
**Pull request by jglick**
Analogous to https://github.com/jenkinsci/git-plugin/pull/403.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Test failures seem to be caused by the svn.jenkins-ci.org decommissioning that I noted a while back on jenkinsci-dev.

**Comment by jglick** [comment]
CC @stephenc

**Comment by jglick** [comment]
> I noted a while back on jenkinsci-dev

specifically [here](https://groups.google.com/d/msg/jenkinsci-dev/8tLnOhHitKI/OShZe6ofCwAJ)

**Comment by stephenc** [comment]
:bee:

**Comment by recena** [comment]
@jglick And me, in the same thread.

**Comment by recena** [comment]
🐝

**Comment by jglick** [comment]
> And me, in the same thread.

Indeed, missed that.

**Pull request merged**
