### PR TITLE
[JENKINS-30774] Simplify the repository validation

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-30774](https://issues.jenkins-ci.org/browse/JENKINS-30774)

jenkins-30774

As part of this PR the option **Validate repository URLs up to the first variable name** will be ignore:

* Users are using parameters for: `hostname`, `basepath`, `branches` etc. In several of them, this option does not work fine because was design for a specific use case.
* The validation message when this options does not work fine is confused.

@reviewbybees, specially @christ66 and @daniel-beck

### CODE REVIEW

**Comment by stephenc** [comment]
:bee:

**Comment by recena** [comment]
@stephenc I'm very happy for your :bee: here.

**Comment by christ66** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Comment by recena** [comment]
@stephenc @christ66 Thanks so much for your time!

**Pull request merged**
