### PR TITLE
[JENKINS-29225] Failed to tag

### PR DESCRIPTION
**Pull request by recena**
https://issues.jenkins-ci.org/browse/JENKINS-29225

jenkins-29225_1

### CODE REVIEW

**Comment by recena** [comment]
@reviewbybees Could you review these changes? Specially, @stephenc.

**Comment by oleg-nenashev** [comment]
The initial implementation seems to be quite strange, but :bee: for the fix

**Comment by recena** [comment]
@oleg-nenashev I agree but the priority was to resolve blocked bugs.

**Comment by oleg-nenashev** [comment]
@recena 
Yes, no complains at all. A refactoring of SVN plugin is another big story

**Comment by recena** [comment]
@oleg-nenashev I would like to spend this month (July) to solve bugs and get a stable version

**Comment by stephenc** [comment]
:bee:

**Comment by christ66** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Pull request merged**
