### PR TITLE
subversion external handling

### PR DESCRIPTION
**Pull request by theKBro**
Solving some problems with externals 

1. same external linked to projekt in different revisions
2. unknown credential for externals on polling

Should also solve: JENKINS-22542

### CODE REVIEW

**Comment by theKBro** [comment]
anyone with write access?
@timja @StefanSpieker

**Comment by timja** [comment]
Sorry I have no way of testing this or can understand it really,

I've just shipped some maintenance fixes to allow tests to run on Java 11 basically.

If you want this shipped the best way would be to request maintainer access as by this PR I assume you actually have an SVN environment and are actively using it in your organisation.

You can add yourself to https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-subversion.yml with your Jenkins project account (the one you would use for Jira), (if you want to do this).

**Comment by theKBro** [comment]
@timja 

> If you want this shipped the best way would be to request maintainer access as by this PR I assume you actually have an SVN environment and are actively using it in your organisation.

Yes, we already tested the changes in our production system for a while now. So how to request maintainer access?

> You can add yourself to https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-subversion.yml with your Jenkins project account (the one you would use for Jira), (if you want to do this).

Would be great but this is also write protected for me.

**Comment by timja** [comment]
Just send a pull request there adding yourself to that list

**Pull request merged**
