### PR TITLE
svnkit 1.9.1

### PR DESCRIPTION
**Pull request by ssl-maxtouch**
SVNKit 1.9.1 passes the unit tests

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Is there any particular justification for the update (bugs in Jenkins JIRA, new features, etc.)? Just interested

**Comment by ssl-maxtouch** [comment]
Yes, we found that 1.9 is better in merges and resolving conflicts, in fact we all use locally TortoiseSVN 1.9.x and it would be great if Jenkins would also use that (if there are no reasons to stick with the old version) without us needing to rebuild the plugin ourselves

**Comment by oleg-nenashev** [comment]
FYI @kuisathaverat

**Comment by imakowski** [comment]
When this will be released?

**Pull request merged**
