### PR TITLE
[JENKINS-35176] Fixes repeated same "Tag this build" links added to builds.

### PR DESCRIPTION
**Pull request by didiez**
See:
 - https://issues.jenkins.io/browse/JENKINS-35176
 - https://issues.jenkins.io/browse/JENKINS-38204

### CODE REVIEW

**Comment by timja** [comment]
This plugin has no maintainers and will need adopting https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/ if you want this mergef

**Review by jglick — COMMENTED** [review]
No test coverage?

**Comment by jglick** [comment]
BTW I think a top priority for any new maintainer should be https://github.com/jenkinsci/subversion-plugin/blob/622e3d5c305ddb54cb992b0003eec755c4fc065c/src/test/java/hudson/scm/SubversionSCMTest.java#L85

**Comment by didiez** [comment]
> No test coverage?

Test added in 955aa91 to prevent regressions

**Review by jglick — APPROVED** [review]

**Comment by timja** [comment]
@didiez you have an invite now at https://github.com/jenkinsci

**Comment by didiez** [comment]
Great! thanks :)

**Pull request merged**
