### PR TITLE
Using SVNKit CLI in preference to native CLI for tests using SubversionSampleRepoRule

### PR DESCRIPTION
**Pull request by jglick**
Follows up #161.

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
You are awesome!

**Comment by recena** [comment]
@jglick I'm still concerned about the test failing.

**Comment by jglick** [comment]
> the failure tests

Sorry, which failures?

**Comment by abayer** [comment]
:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Pull request merged**
