### PR TITLE
[JENKINS-31155] Ability to retrieve a single revision

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/12; analogous to https://github.com/jenkinsci/git-plugin/pull/433.

Subsumes #164.

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
🐝  and 👍

**Comment by abayer** [comment]
:bee:

**Comment by abayer** [comment]
re-:bee:

**Comment by jglick** [comment]
@reviewbybees done

**Pull request merged**
