### PR TITLE
Upgrade to svnkit 1.8.14.

### PR DESCRIPTION
**Pull request by mdiers**
SVNKit 1.8.14, released 10 Oct 2016, provides [a number of bug fixes](https://svn.svnkit.com/repos/svnkit/tags/1.8.14/CHANGES.txt).
It also addresses [SVNKIT-672](https://issues.tmatesoft.com/issue/SVNKIT-672), vastly improving performance on 32-bit Linux.

### CODE REVIEW

**Comment by recena** [comment]
LGTM, I hope to cut a new release tomorrow!

**Comment by recena** [comment]
@mdiers Did you face with something like that?

```
[ERROR] Failed to execute goal on project subversion: Could not resolve dependencies for project org.jenkins-ci.plugins:subversion:hpi:2.7-SNAPSHOT: Failed to collect dependencies at org.tmatesoft.svnkit:svnkit:jar:1.8.14 -> com.trilead:trilead-ssh2:jar:1.0.0-build221: Failed to read artifact descriptor for com.trilead:trilead-ssh2:jar:1.0.0-build221: Could not transfer artifact com.trilead:trilead-ssh2:pom:1.0.0-build221 from/to mavenTMateSoftReleasesRepository (https://maven.tmatesoft.com/content/repositories/releases/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

I've just tried [this](https://support.sonatype.com/hc/en-us/articles/213465088-Maven-is-unable-to-connect-to-Nexus-after-configuring-Nexus-to-use-SSL-) but it seems does not work.

**Comment by recena** [comment]
@mdiers Fixed.

**Comment by mdiers** [comment]
Thanks!

**Comment by jglick** [comment]
Libraries used by Jenkins plugins not in Maven Central must be uploaded to the Jenkins repository. This change is giving me errors. I will see if I can fix it.

**Pull request merged**
